hongOS_project/hongOS_project/urls.py
from django.contrib import admin
from django.urls import path
from hongOS_app.views import clasificar, loginView, registro, home, logoutView, busqueda, info, cargar
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clasificar/', clasificar),
    path('cargar/', cargar),
    path('registro/', registro),
    path('info/', info),
    path('login/', loginView),
    path('home/', home),
    path('', home,name='home'),
    path('logout/',logoutView),
    path('busqueda', busqueda, name='busqueda'),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hongOS_project/hongOS_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Imagen(models.Model):
    file_name = models.ImageField(upload_to='imagenes_hongos')


class HongOSUser(models.Model):
    user =  models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(unique=True)

class Hongos(models.Model):

    def image_upload(self,filename):
        return 'imagenes_hongos/'+str(self.uploader.user)+'/'+str(filename)

    nombre = models.CharField(max_length=20, null=False)
    prob = models.FloatField(max_length=20, null=False)
    uploader = models.ForeignKey(HongOSUser, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to=image_upload)
    nombre2 = models.CharField(max_length=20)
    prob2 = models.FloatField(max_length=20)
    nombre3 = models.CharField(max_length=20)
    prob3 = models.FloatField(max_length=20)

class ImagenDataset(models.Model):
    especie = models.CharField(max_length=20, null=False)
    tamanio = models.FloatField(null=False)
    resolucion = models.CharField(max_length=10, null=False)
    nombre_archivo = models.CharField(max_length=50, null=False)

hongOS_project/hongOS_app/forms.py
from django import forms
from .models import Imagen, HongOSUser
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class ImagenForm(forms.ModelForm):
    class Meta:
        model = Imagen
        fields = ('file_name',)

class HongOSUserForm(forms.ModelForm):

    class Meta:
        model = HongOSUser
        fields = (
            'email',
        )  #If we want all parameters we can just use fields = "_all_"
        error_messages = {
            'email': {
                'unique':("Ya existe un usuario con este correo electrónico"),
            },
        }

class UserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'password1','password2')
        error_messages = {
            'username': {
                'unique':("Ya existe un usuario con este nombre de usuario"),
            },
        }

hongOS_project/hongOS_app/views.py
import email
from fileinput import filename
from unicodedata import name
from django.shortcuts import render, redirect
from fastbook import load_learner
from pathlib import Path
import os
from django.contrib.auth.models import User
from .models import Hongos, HongOSUser, Imagen, ImagenDataset
from .forms import ImagenForm, HongOSUserForm, UserForm
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.conf import settings
import PIL
from PIL import Image

# Create your views here.


@login_required
def clasificar(request):
    if request.method == 'GET':
        form = ImagenForm(request.POST or None, request.FILES or None)
        return render(request, 'clasificar.html', {'form': form, 'method': request.method})
    if request.method == 'POST':
        form = ImagenForm(request.POST or None, request.FILES or None)
        if request.POST.get('file_name') == '':
            messages.info(request, 'No ha adjuntado ninguna imagen')
            return redirect('/clasificar/')
        if form.is_valid and HongOSUser.objects.filter(user=request.user.id).count() != 0:
            form.save()
            username = request.user.username
            imagePath = os.path.join(settings.BASE_DIR, 'media/imagenes_hongos/' +
                                     str(form.cleaned_data.get('file_name')).replace(' ', '_').replace('(', '').replace(')', '').replace('ñ', ''))

            # Buscamos si la imagen está en el set de entrenamiento

            tamanio = os.stat(imagePath).st_size
            picture = PIL.Image.open(imagePath)
            alto, ancho = picture.size
            resolucion = str(alto) + 'x' + str(ancho)
            nombre_archivo = form.cleaned_data.get('file_name')
            if ImagenDataset.objects.filter(tamanio=tamanio, resolucion=resolucion).count() != 0 or ImagenDataset.objects.filter(nombre_archivo=nombre_archivo).count() != 0:
                messages.info(
                    request, 'Es probable que la imagen que haya subido se haya usado para entrenar el modelo de clasificación.')

            for f in Hongos.objects.filter(uploader=HongOSUser.objects.filter(user=request.user.id)[0]):
                savedImage = PIL.Image.open(f.imagen)
                nombre_archivo2 = f.imagen.url.split('/')[-1]
                print(nombre_archivo2)
                alto2, ancho2 = savedImage.size
                resolucion2 = str(alto2) + 'x' + str(ancho2)
                if (nombre_archivo2 == nombre_archivo or resolucion2 == resolucion):
                    messages.info(
                        request, 'Es probable que ya hayas subido esta imagen.')
                    ruta = 'imagenes_hongos/' + \
                        request.user.username+'/'+str(nombre_archivo2)
                    print(ruta)
                    hongo = Hongos.objects.filter(imagen=ruta)[0]
                    return render(request, 'clasificar.html', {'imagePath': imagePath, 'method': request.method, 'hongo': hongo})

            path = Path().resolve()
            learner = load_learner(os.path.join(
                settings.BASE_DIR, '89,1207.pkl'))
            clases = ['Agaricus', 'Amanita', 'Boletus', 'Cortinarius',
                      'Entoloma', 'Hygrocybe', 'Lactarius', 'Russula', 'Suillus']
            pred, pred_idx, probs = learner.predict(imagePath)
            zipped = list(zip(probs, clases))
            srtd = sorted(zipped, key=lambda t: t[0], reverse=True)
            next2 = srtd[1:3]

            hongo2Prob, hongo2Label = next2[0]
            hongo3Prob, hongo3Label = next2[1]

            hongo2Prob = round(hongo2Prob.item()*100, 2)
            hongo3Prob = round(hongo3Prob.item()*100, 2)

            prob = round(probs[pred_idx].item()*100, 2)
            userHongOS = HongOSUser.objects.filter(user=request.user.id)[0]
            hongo = Hongos(nombre=pred, prob=prob, uploader=userHongOS,
                           imagen=form.cleaned_data.get('file_name'), nombre2=hongo2Label, prob2=hongo2Prob, nombre3=hongo3Label, prob3=hongo3Prob)
            hongo.save()
            os.remove(imagePath)
            return render(request, 'clasificar.html', {'imagePath': imagePath, 'method': request.method, 'hongo': hongo})
        else:
            messages.info(
                request, 'El usuario con el que está intentando acceder no está correctamente creado, por favor, cree otro o inténtelo de nuevo')
            return redirect('/login/')


@login_required
def cargar(request):
    if request.method == 'GET':
        return render(request, 'cargar.html', {'method': request.method})
    if request.method == 'POST':
        directorios = os.listdir(os.path.join(settings.BASE_DIR, 'Mushrooms'))
        for directorio in directorios:
            imagenes = os.listdir(os.path.join(
                settings.BASE_DIR, 'Mushrooms/'+directorio))
            print(len(imagenes))
            for imagen in imagenes:
                ruta = os.path.join(settings.BASE_DIR,
                                    'Mushrooms/'+directorio+'/'+imagen)
                tamanio = os.stat(ruta).st_size
                picture = PIL.Image.open(ruta)
                alto, ancho = picture.size
                resolucion = str(alto) + 'x' + str(ancho)
                nombre_archivo = imagen
                imagenDataset = ImagenDataset(
                    especie=directorio, tamanio=tamanio, resolucion=resolucion, nombre_archivo=nombre_archivo)
                imagenDataset.save()
    return render(request, 'cargar.html', {'method': request.method})


def registro(request):
    submitted = False
    if request.method == "POST":
        form1 = UserForm(request.POST)
        form2 = HongOSUserForm(request.POST, request.FILES)
        if form1.is_valid() and form2.is_valid():
            form1.save()
            gameetUser = form2.save(commit=False)
            gameetUser.user = form1.save()
            gameetUser.save()
            messages.success(request, 'Tu cuenta se creó correctamente!')
            return HttpResponseRedirect('/login')
    else:
        form1 = UserForm()
        form2 = HongOSUserForm()
    return render(request, 'registro.html', {'form1': form1, 'form2': form2})


@login_required
def info(request):
    return render(request, 'info.html', {})


@login_required
def busqueda(request):
    if request.method == "POST":
        usuario = HongOSUser.objects.filter(user=request.user.id)[0]
        busqueda = request.POST.get('busqueda')
        hongos = list(Hongos.objects.filter(
            nombre__contains=busqueda, uploader=usuario))

        if len(busqueda) != 0:
            return render(request, 'busqueda.html', {'busqueda': busqueda, 'hongos': hongos})
        else:
            return redirect('/home/')
    else:
        return render(request, 'busqueda.html', {})


def loginView(request):

    if request.method == 'POST':
        if User.objects.filter(
                username=request.POST.get('username')).count() != 0:
            userID = User.objects.filter(
                username=request.POST.get('username'))[0].id
            if HongOSUser.objects.filter(user=userID).count() != 0:

                username = request.POST.get('username')
                password = request.POST.get('password')

                user = authenticate(
                    request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    messages.success(
                        request, 'La sesión se inició correctamente')
                    return redirect('/home/')
                else:
                    messages.info(
                        request, 'El usuario o contraseña son incorrectos')
                    return redirect('/login/')
            else:
                messages.info(
                    request, 'El usuario con el que está intentando acceder no está correctamente creado, por favor, cree otro o inténtelo de nuevo')
                return redirect('/logout/')
        else:
            messages.info(
                request, 'El usuario no existe, por favor, regístrese')
            return render(request, 'login.html', {})
    if request.method == 'GET':
        return render(request, 'login.html', {})


@login_required
def home(request):
    hongOSUserID = HongOSUser.objects.filter(user=request.user.id)[0].id
    hongos_from_this_user = Hongos.objects.filter(uploader=hongOSUserID)[:10]
    return render(request, 'home.html', {'hongos': hongos_from_this_user})


@login_required
def logoutView(request):
    logout(request)
    messages.success(request, 'La sesión se cerró correctamente')
    return redirect('/login/')

hongOS_project/hongOS_app/templates/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=0.7">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <script src="https://code.jquery.com/jquery-3.6.1.js"
        integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"></script>
    <title>{%block title%}Base{%endblock%}</title>
</head>

<body>

    <style>
        #github {
            margin-left: -4;
            margin-right: 10;
        }

        #barra-busqueda {
            margin: auto;
        }

        #logout {
            margin-left: 5;
        }

        .menu-icon {
            display: none;
        }

        #logout-mobile {
            display: none;
        }

        @media only screen and (max-width: 1000px) {

            #logout-mobile {
                display: inline;
            }

            #barra-busqueda {
                width: 50%;
            }

            .menu-icon {
                display: inline;
                cursor: pointer;
            }

            #logout {
                display: none;
            }

            #navbar {
                outline-style: solid;
                outline-width: 0.5px;
                outline-color: #131313;
                text-align: center;
                display: block;
                background: #bbbbbb;
                right: 0;
                position: absolute;
                top: 60px;
                right: 0;
                z-index: 1;
            }

            #complete-navbar {
                margin-bottom: 5px;
            }

        }
    </style>

    <nav id="complete-navbar" class="navbar navbar-expand-lg navbar-light bg-light">
        <a id="github" href="https://github.com/pabsanort2/hongOS" target="_blank" rel="noopener noreferrer"><img
                src="{% static 'github.png' %}" alt="enlace github"></a>
        <a class="navbar-brand" href="/home">HongOS</a>
        <ul id="navbar" class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" id="home" href="/home">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" id="clasificar" href="/clasificar">Clasificar <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/info">Info <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a id="logout-mobile" type="button" class="nav-link" href="/logout">Logout</a>
            </li>
        </ul>
        <ul class="navbar-nav mr-auto" id="busqueda">
            <form class="form-inline my-2 my-lg-0" method="POST" action="{%url 'busqueda'%}">
                {%csrf_token%}
                <input class="form-control mr-sm-2" type="search" placeholder="Buscar hongos" aria-label="Search"
                    name="busqueda" id="barra-busqueda">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit" id="submit-busqueda"><svg
                        xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-search" viewBox="0 0 16 16">
                        <path
                            d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                    </svg></button>
            </form>
        </ul>

        <img class="menu-icon" src="{% static 'menu-icon.png' %}" alt="menu-icon" onclick="toggleMenu()" />
        <a id="logout" type="button" class="btn btn-outline-danger" href="/logout">Logout</a>
    </nav>

    <script>


            var menuList = document.getElementById("navbar");
            menuList.style.display = "none";

            function toggleMenu() {
                if (menuList.style.display == "none") {
                    menuList.style.display = "inline";
                } else {
                    menuList.style.display = "none";
                }
            }
            if(screen.width >= 1000){
                    menuList.style.display = "";
                }
    </script>

    {% block content %}{% endblock %}
</body>

</html>

hongOS_project/hongOS_app/templates/cargar.html
{% extends "base.html" %}

<html lang="es">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=0.7">
  <title>{%block title%}HongOS{%endblock%}</title>
</head>

<body>

  {% block content %}

  <style>

    #messages{
          margin-top: 10px;
          margin-left: 715px;
          width: 30%;
          text-align: center;
      }

    #file_form {
      position: absolute;
      top: 50%;
      left: 50%;
      margin-top: -330px;
      margin-left: -200px;
      width: 500px;
      height: 200px;
      /* border: 4px dashed rgb(119, 119, 119); */
    }

    #form_p {
      width: 100%;
      height: 100%;
      text-align: center;
      line-height: 170px;
      color: #a8a5a5;
      font-family: Arial;
    }

    #id_file_name {
      position: absolute;
      margin: 0;
      padding: 0;
      width: 100%;
      height: 100%;
      outline: none;
      opacity: 0;
    }

    #form_button {
      margin: 0;
      color: rgb(255, 255, 255);
      background: #16a085;
      border: none;
      width: 508px;
      height: 35px;
      margin-left: -4px;
      border-radius: 4px;
      border-bottom: 4px solid #117A60;
      transition: all .2s ease;
      outline: none;
    }


    #form_button:hover {
      background: #149174;
      color: #0C5645;
    }

    #form_button:active {
      border: 0;
    }

    .row{
      margin-top: 1%;
    }
    
  </style>

  {%for message in messages%}
    <div id="messages" class="alert alert-warning" role="alert">
        <p>{{message}}</p>
    </div>
    {%endfor%}

  {% if method == "GET" %}
  <form id='file_form' action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
      <button id='form_button' type="submit">Cargar hongos</button>
    </div>
  </form>

  {% endif %}

  {% if method == "POST" %}

  {% if messages %}
    <div>
      <p>Ha habido un problema al cargar los hongos</p>
    </div>
  {% else %}
  <div>
    <p>Los hongos se han cargado correctamente</p>
  </div>
  {% endif %}

  {% endif %}
  {% endblock %}
</body>

</html>

hongOS_project/hongOS_app/templates/clasificar.html
{% extends "base.html" %}

<html lang="es">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=0.7">
  <title>{%block title%}HongOS{%endblock%}</title>
</head>

<body>

  {% block content %}

  <style>
    #messages {
      margin: auto;
      margin-top: 5px;
      margin-bottom: 5px;
      padding: 10px;
      width: 30%;
      text-align: center;
    }

    #file_form {
      position: absolute;
      top: 50%;
      left: 50%;
      margin-top: -330px;
      margin-left: -200px;
      width: 500px;
      height: 200px;
      border: 4px dashed rgb(119, 119, 119);
    }

    #form_p {
      width: 100%;
      height: 100%;
      text-align: center;
      line-height: 170px;
      color: #a8a5a5;
      font-family: Arial;
    }

    #id_file_name {
      position: absolute;
      margin: 0;
      padding: 0;
      width: 100%;
      height: 100%;
      outline: none;
      opacity: 0;
    }

    #form_button {
      margin: 0;
      color: rgb(255, 255, 255);
      background: #16a085;
      border: none;
      width: 508px;
      height: 35px;
      margin-left: -4px;
      border-radius: 4px;
      border-bottom: 4px solid #117A60;
      transition: all .2s ease;
      outline: none;
    }


    #form_button:hover {
      background: #149174;
      color: #0C5645;
    }

    #form_button:active {
      border: 0;
    }

    .row {
      margin-top: 1%;
    }

    @media only screen and (max-width: 1000px) {

      #form_button {
        width: 254px;
      }

      #file_form {
        margin-left: -120px;
        width: 250px;
      }

      #form_p {
        font-size: 13px;
      }

      ul img {
        margin: auto;
      }

      #texto-hongos {
        margin-top: 5px;
        margin: auto;
        text-align: center;
      }

      #container {
        width: 95%;
        margin: auto;
      }

    }
  </style>

  {%for message in messages%}
  <div id="messages" class="alert alert-warning" role="alert">
    <p>{{message}}</p>
  </div>
  {%endfor%}

  {% if method == "GET" %}

  <script type="text/javascript">
    function changeText() {
      document.getElementById('form_p').innerText = document.getElementById("id_file_name").value.split("\\")[2]
    }
  </script>

  <form id='file_form' action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div id="modulo-subida">
      <input type="file" onchange="changeText()" name="file_name" accept="image/*" id="id_file_name">
      <p id="form_p">Haz click aquí para subir tu imagen</p>
      <button id='form_button' type="submit">Subir</button>
    </div>
  </form>

  {% endif %}

  {% if method == "POST" %}

  <div id="container" class="row">
    <div class="col-lg-8 mx-auto">
      <!-- List group-->
      <ul class="list-group shadow">
        <!-- list group item-->
        <li class="list-group-item">
          <!-- Custom content-->
          <div class="media align-items-lg-center flex-column flex-lg-row p-3">
            <div id='texto-hongos' class=" media-body order-2 order-lg-1">
              <h5 class="mt-0 font-weight-bold mb-2">El hongo de la imagen es del género: {{hongo.nombre}}</h5>
              <!-- <p class="font-italic text-muted mb-0 small"></p> -->
              {%if hongo.prob >= 1%}
              <h6 class="font-weight-bold my-2">Probabilidad: {{hongo.prob}}%</h6>
              {%endif%}
              {%if hongo.prob2 >= 1 or hongo.prob3 >= 1 %}
              <h6 class="font-weight-bold my-2">También puede ser:</h6>
              <ul class="list-group list-group-flush">
                {%if hongo.prob2 >= 1%}
                <li class="list-group-item">{{hongo.nombre2}}, probabilidad: {{hongo.prob2}}%</li>
                {%endif%}
                {%if hongo.prob3 >= 1%}
                <li class="list-group-item">{{hongo.nombre3}}, probabilidad: {{hongo.prob3}}%</li>
                {%endif%}
              </ul>
              {%endif%}
            </div><img src='{{hongo.imagen.url}}' alt='{{hongo.nombre}}' width="200" class="ml-lg-5 order-1 order-lg-2">
          </div> <!-- End -->
        </li> <!-- End -->
      </ul> <!-- End -->
    </div>
  </div>

  {% endif %}
  {% endblock %}
</body>

</html>

hongOS_project/hongOS_app/templates/login.html
{%load static%}

<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=0.7">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <title>HongOS</title>
</head>

<body>

    <style>
        div {
            width: 20%;
            text-align: center;
            margin: 0 auto;
        }

        #principal_div {
            margin-top: 10%;
        }

        #messages{
            margin-top: 1%;
            width: 30%;
        }

        * {
            box-sizing: border-box;
        }

        @media only screen and (max-width: 1000px) {
            div{
                width: 30%;
            }
        }

    </style>

    {%for message in messages%}
    <div id="messages" class="alert alert-warning" role="alert">
        <p>{{message}}</p>
    </div>
    {%endfor%}

    <div id=principal_div class="form-outline mb-4"></div>
    <form method="POST" class="form-signin">
        {% csrf_token %}
        <div class="text-center">
            <p>Iniciar sesión</p>
        </div>

        <!-- User input -->
        <div class="form-outline mb-4">
            <input type="text" id="form2Example1" class="form-control" placeholder="Usuario" name="username" />
            <label class="form-label" for="label_username"></label>
        </div>

        <!-- Password input -->
        <div class="form-outline mb-4">
            <input type="password" id="id_password" class="form-control" placeholder="Contraseña" name="password" />
            <label class="password-label" for="password-label"></label>
        </div>

        <!-- 2 column grid layout for inline styling -->

        <!-- Submit button -->
        <div class="text-center">
            <button type="submit" class="btn btn-primary btn-block mb-4">Iniciar sesión</button>
        </div>
    </form>
    <!-- Register buttons -->
    <div class="text-center">
        <p>¿Aún no te has registrado? <a href="/registro/">Regístrate!</a></p>
    </div>

</body>

</html>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

hongOS_project/hongOS_app/templates/registro.html
{%load static%}

<html lang="es">

<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=0.7e">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <title>HongOS</title>
</head>

<body>

    <style>
        div {
            width: 50%;
            text-align: center;
            margin: 0 auto;
        }

        #principal_div {
            margin-top: 10%;
        }

        #messages {
            margin-top: 1%;
        }

        #errors {
            margin-top: 1%;
        }

        * {
            box-sizing: border-box;
        }

        @media only screen and (max-width: 1000px) {
            div{
                width: 70%;
            }
        }
    </style>

    {%for message in messages%}
    <div id='messages' class="text-center">
        <p>{{message}}</p>
    </div>
    {%endfor%}

    <!-- <div class="content-section">

        <form enctype='multipart/form-data' method='POST'> 

            {% csrf_token %}
            <legend>Crea tu cuenta</legend>
            {{form1.username.label}}
            {{form1.username}}
            
            <br>

            {{form2.email.label}}
            {{form2.email}}

            <br>

            {{form1.password1.label}}
            {{form1.password1}}

            <br>

            {{form1.password2.label}}
            {{form1.password2}} -->

    <!-- Tambien se puede hacer asi
            {% for field in form %}
                {field.label}
                {field}
            {%endfor%}-->
    <!-- <div class="submit-button"><button type="submit">Aceptar</button></div>
        </form> -->

    {% if form1.errors %}
    {% for field in form1 %}
    {% for error in field.errors %}
    <div id=errors class="alert alert-danger" role="alert">
        {{ error|escape }}
    </div>
    {% endfor %}
    {% endfor %}
    {% endif %}

    {% if form2.errors %}
    {% for field in form2 %}
    {% for error in field.errors %}
    <div id=errors class="alert alert-danger" role="alert">
        {{ error|escape }}
    </div>
    {% endfor %}
    {% endfor %}
    {% endif %}

    <!-- {%for error in form1.errors%}
    <div class="alert alert-danger" role="alert">
        {{error.0}}
    </div>
    {%endfor%}

    {%for error in form2.errors%}
    <div class="alert alert-danger" role="alert">
        {{error.0}}
    </div>
    {%endfor%}
    </div> -->

    <div id="principal_div" role="tabpanel" aria-labelledby="tab-register">
        <div class="text-center">
            <p>Registrarse</p>
        </div>
        <form enctype='multipart/form-data' method='POST'>
            {% csrf_token %}
            <!-- Username input -->
            <div class="form-outline mb-4">
                <input type="text" name="username" required id="id_username" class="form-control" placeholder='{{form1.username.label}}' />
            </div>

            <!-- Email input -->
            <div class="form-outline mb-4">
                <input type="email" name="email" maxlength="254" required id="id_email" class="form-control"
                    placeholder="{{form2.email.label}}" />
            </div>

            <!-- Password input -->
            <div class="form-outline mb-4">
                <input t type="password" name="password1" autocomplete="new-password" required id="id_password1"
                    class="form-control" placeholder="{{form1.password1.label}}" />
            </div>

            <!-- Repeat Password input -->
            <div class="form-outline mb-4">
                <input type="password" name="password2" autocomplete="new-password" required id="id_password2"
                    class="form-control" placeholder="{{form1.password2.label}}" />
            </div>

            <!-- Submit button -->
            <div class="form-outline mb-4">
                <button type="submit" class="btn btn-primary btn-block mb-3">Registrarse</button>
            </div>
        </form>
        <div class="text-center">
            <p>¿Ya tienes una cuenta? <a href="/login/">Inicia sesión aquí!</a></p>
        </div>
    </div>
    </div>

</body>

</html>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">